backend:
  name: git-gateway
  branch: main

site_url: https://testedeteste.netlify.app

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "src/data/content.yml"
        label: "Página Principal"
        name: "home"
        fields:
          - { label: "Link de Afiliação Global", name: "affiliate_link", widget: "string" }
          - label: "Recursos Partilhados"
            name: "shared_assets"
            widget: "object"
            fields:
              - { label: "Imagem da Seta", name: "arrow_image", widget: "image" }
          - label: "Secção Herói"
            name: "hero_section"
            widget: "object"
            fields:
              - { label: "Imagem do Avião", name: "plane_image", widget: "image" }
              - { label: "Texto do Botão Principal", name: "button_text", widget: "string" }
              - { label: "ID do Vídeo do YouTube", name: "video_id", widget: "string" }
          - label: "Secção de Prémios"
            name: "prize_section"
            widget: "object"
            fields:
              - { label: "Imagem do Prémio", name: "prize_image", widget: "image" }
              - { label: "Imagem das Estrelas", name: "stars_image", widget: "image" }
          - label: "Secção Clube VIP"
            name: "vip_club_section"
            widget: "object"
            fields:
              - { label: "Imagem do Clube VIP", name: "vip_image", widget: "image" }
          - label: "Secção de Registo"
            name: "registration_section"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Imagem do Formulário", name: "form_image", widget: "image" }
          - label: "Secção Bónus Final"
            name: "final_bonus_section"
            widget: "object"
            fields:
              - { label: "Imagem do Bónus", name: "bonus_image", widget: "image" }
              - { label: "Texto do Botão", name: "button_text", widget: "string" }
